cpana_classifieds_homepage:
    path:     /classifieds
    defaults: { _controller: CPANAClassifiedsBundle:Default:index }

cpana_classifieds_categories_index:
    path:     /classifieds/categories
    defaults: { _controller: CPANAClassifiedsBundle:Categories:index }

cpana_classifieds_countries_index:
    path:     /classifieds/countries
    defaults: { _controller: CPANAClassifiedsBundle:Countries:index }

cpana_classifieds_countries_regions:
    path:     /classifieds/countries/regions
    defaults: { _controller: CPANAClassifiedsBundle:Countries:regions }

cpana_classifieds_public_ads_show_all:
    path:     /classifieds/ads/showall
    defaults: { _controller: CPANAClassifiedsBundle:Pub\Ads:showAll }


cpana_classifieds_admin_category_index:
    path:     /admin/classifieds/category
    defaults: { _controller: CPANAClassifiedsBundle:Admin\Category:index }
